---

- name: set up redirect site
  sudo: yes
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} backup={{ item.backup }}
  with_items:
      - { src: 'redirects', dest: '/etc/nginx/sites-available/redirects', owner: 'root', group: 'root', mode: 644, backup: 'no' }
  tags:
    - site
    - setup

- name: enable redirect site
  sudo: yes
  file:
    src: /etc/nginx/sites-available/redirects
    dest: /etc/nginx/sites-enabled/redirects
    owner: root
    group: root
    state: link
  tags:
    - site
    - setup
