---

- name: copy public key
  authorized_key:
    user: "{{ ansible_ssh_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags:
    - setup
    - ssh

- name: update APT cache
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - setup
    - locale

- name: upgrade 
  apt: upgrade=dist
  tags:
    - setup
    - maintenance

- name: install base packages
  apt:
    name: ['cpulimit', 'fail2ban', 'htop', 'iftop', 'iotop', 'language-pack-en-base', 'software-properties-common', 'tmux', 'wget', 'vim']
    state: latest
  tags:
    - setup
    - locale

- name: locale setup
  shell: locale-gen en_US.UTF-8
  shell: dpkg-reconfigure locales
  shell: update-locale {{ item }}
  with_items:
    - LANGUAGE="en_US.UTF-8"
    - LANG="en_US.UTF-8"
    - LC_ALL="en_US.UTF-8"
  sudo: yes
  tags:
    - setup
    - locale

- name: timezone setup
  shell: timedatectl set-timezone Europe/Lisbon
  sudo: yes
  tags:
    - setup
    - configuration

- name: limit open files for piku
  lineinfile: dest=/etc/security/limits.conf line="{{ piku_username }} {{ item.key }} nofile {{ item.value }}"
  with_dict: "{{ limits }}"
  sudo: yes
  tags:
    - setup
    - tuning

- name: limit priority for omsagent
  lineinfile: dest=/etc/security/limits.conf line="omsagent - priority 30"
  sudo: yes
  tags:
    - setup
    - tuning

- name: sysctl tuning
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: "{{ kernel }}"
  sudo: yes
  tags:
    - setup
    - tuning

- name: alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ custom_ssh_port }}"
  notify: "restart sshd"
  
- name: set up cgconfig and rc.local
  sudo: yes
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} backup={{ item.backup }}
  with_items:
      - { src: 'cgconfig.conf', dest: '/etc/cgconfig.conf', owner: 'root', group: 'root', mode: 644, backup: 'no' }
      - { src: 'rc.local', dest: '/etc/rc.local', owner: 'root', group: 'root', mode: 755, backup: 'no' }
      - { src: 'cgrules.conf', dest: '/etc/cgrules.conf', owner: 'root', group: 'root', mode: 644, backup: 'no' }
  tags:
    - setup
