---

- name: install package dependencies
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - git
    - build-essential
    - libxml2-dev
    - libxslt1-dev
    - libjpeg-dev
    - zlib1g-dev
    - python-dev
    - python-virtualenv 
    - python-pip  
    - uwsgi 
    - uwsgi-plugin-python
    - uwsgi-plugin-python3
    - uwsgi-plugin-asyncio-python3
    - uwsgi-plugin-gevent-python
    - uwsgi-plugin-tornado-python
    - incron
    - nginx
  tags:
    - piku
    - setup

- name: install click
  sudo: yes
  shell: pip install -U click pip
  tags:
    - piku
    - setup

- name: add piku user
  sudo: yes
  user: name=piku createhome=yes comment='PaaS access' group=www-data state=present
  tags:
    - piku
    - security

- name: copy files
  sudo: yes
  copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} backup={{ item.backup }}
  with_items:
      - { src: 'nginx.default.dist', dest: '/etc/nginx/sites-available/default', owner: 'root', group: 'root', mode: 644, backup: 'yes' }
      - { src: 'incron.dist', dest: '/etc/incron.d/piku', owner: 'root', group: 'root', mode: 644, backup: 'no' }
      - { src: 'uwsgi.service', dest: '/etc/systemd/system/uwsgi.service', owner: 'root', group: 'root', mode: 644, backup: 'yes' }
      - { src: 'piku.py', dest: '/home/piku/piku.py', owner: 'root', group: 'root', mode: 755, backup: 'no' }
  tags:
    - piku
    - setup

- name: setup piku
  sudo: yes
  shell: python /home/piku/piku.py setup && python /home/piku/piku.py setup:ssh /tmp/pubkey
  tags:
    - piku
    - setup
  

- name: setup services
  sudo: yes
  shell: systemctl enable nginx && systemctl restart nginx
  shell: systemctl enable incron && systemctl restart incron
  shell: systemctl enable uwsgi && systemctl restart uwsgi
  tags:
    - piku
    - services
    - setup
